### ISSUE TITLE
Feature: add elevation to GeoJSON output

### ISSUE THREAD

**Issue by voj** [GNS-Science/solvis#46]
* solvis version: 0.12.3
* Python version: 3.11.9
* Operating System: Jupyter Notebook Docker image running under Windows 11

### Description

Running the following code returns 2-dimensional GeoJSON. We want elevation data to be included, for example to render 3D visualisations.

```python
import json
from IPython.display import GeoJSON

# NSHM libraries ..
import nzshm_model as nm
import solvis

# we need a matching source_logic_tree (CBC do we really ???)
slt = nm.get_model_version("NSHM_v1.0.4").source_logic_tree

# load the composite_solution using the source logic tree
csol = solvis.CompositeSolution.from_archive("../NSHM_v1.0.4_CompositeSolution.zip", slt)

# get the the Crustal FaultSystemSolution
fss = csol._solutions['CRU']
gj = json.loads(fss.fault_surfaces().to_json())
```

This is sample code from `solvis-jupyterlab`

We need a decision on whether to include elevation as `depth in km` as is done in `openSHA`, or as `elevation in m` as is expected by all 3rd party tools.

See https://github.com/GNS-Science/solvis/tree/feature/46-3d-geojson for a partial solution.

**Comment by chrisbc** [comment]
this is closed by #48 inversion_solution_file
